"""Keep the lectures in sync with FIELD_GUIDE.md (the single source of the field guide).

For every lecture that some item of FIELD_GUIDE.md cites, as in "(L10, L12)", this script writes one notes cell,
"Field guide: what this lecture adds", with that lecture's items grouped by stage, and a link to the whole guide. The
cell is placed just before "See you next class" (or the last cell; appendices may follow it) and replaced on every run. It also
regenerates the index by lecture at the end of FIELD_GUIDE.md.

Usage, from the root of the repository:  python Lectures/sync_field_guide.py
"""
import re
from collections import defaultdict
from pathlib import Path

import nbformat

ROOT = Path(__file__).resolve().parents[1]
GUIDE = ROOT / "FIELD_GUIDE.md"
URL = "https://github.com/bessagroup/3dasm_course/blob/main/FIELD_GUIDE.md"
TAG = "field_guide"                                     # metadata key of the generated cells
TITLE = "## Field guide: what this lecture adds"


def read_items(text):
    """[((part, group), item text, [lecture numbers])] for every bullet (multi-line bullets joined). Parts are the "## "
    headings (key concepts, good practices), groups the "### " headings (themes, stages of a project)."""
    items, part, group, current = [], None, None, None
    for line in text.split("<!-- BEGIN INDEX")[0].splitlines():
        if line.startswith("## "):
            part = line[3:].strip()
        elif line.startswith("### "):
            group = line[4:].strip()
        elif line.startswith("- "):
            current = [(part, group), line[2:].strip()]
            items.append(current)
        elif current is not None and line.startswith("  ") and line.strip():
            current[1] += " " + line.strip()
        elif not line.strip():
            current = None
    out = []
    for stage, body in items:
        m = re.search(r"\((L\d+(?:,\s*L\d+)*)\)\s*$", body)
        assert m, f"item without lectures: {body[:60]}"
        out.append((stage, body[:m.start()].rstrip(), [int(x) for x in re.findall(r"L(\d+)", m.group(1))]))
    return out


def lecture_path(n):
    for p in (ROOT / f"Lectures/Lecture{n:02d}/3dasm_Lecture{n}.ipynb", ROOT / f"Lectures/Lecture{n}/3dasm_Lecture{n}.ipynb"):
        if p.exists():
            return p
    raise FileNotFoundError(f"Lecture {n}")


def cell_text(n, items):
    by_part = defaultdict(lambda: defaultdict(list))
    for (part, group), body, lectures in items:
        if n in lectures:
            by_part[part][group].append(body)
    lines = [TITLE, ""]
    for part, groups in by_part.items():
        lines += [f"### {part}", ""]
        for group, bodies in groups.items():
            lines.append(f"**{group}**")
            lines += [f"- {b}" for b in bodies]
            lines.append("")
    lines.append(f"The whole [field guide]({URL}) collects the key concepts and good practices of every lecture.")
    return "\n".join(lines)


def sync_lecture(n, items):
    path = lecture_path(n)
    nb = nbformat.read(path, 4)
    nb.cells = [c for c in nb.cells if not c.metadata.get(TAG)]
    cell = nbformat.v4.new_markdown_cell(cell_text(n, items))
    cell.metadata.update({TAG: True, "slideshow": {"slide_type": "notes"}})
    cell["id"] = f"field-guide-l{n}"
    ends = [i for i, c in enumerate(nb.cells) if "See you next class" in c.source]
    nb.cells.insert(ends[-1] if ends else len(nb.cells) - 1, cell)   # before "See you next class" (appendices may follow)
    nbformat.write(nb, path)
    return path


def sync_index(text, items):
    by_lecture = defaultdict(list)
    for (part, group), body, lectures in items:
        title = re.match(r"\*\*(.+?)\*\*", body)
        kind = "concept" if part.lower().startswith("key concept") else "practice"
        g = group.split(". ", 1)[-1]
        for n in lectures:
            name = (title.group(1) if title else body[:60]).rstrip(".:")
            by_lecture[n].append(f"{name} *({kind}: {g})*")
    lines = ["<!-- BEGIN INDEX (generated by Lectures/sync_field_guide.py: do not edit by hand) -->", "",
             "## Index by lecture", ""]
    for n in sorted(by_lecture):
        lines.append(f"- **Lecture {n}**")
        lines += [f"    - {entry}" for entry in by_lecture[n]]
    lines += ["", "<!-- END INDEX -->"]
    head = text.split("<!-- BEGIN INDEX")[0]
    return head + "\n".join(lines) + "\n"


if __name__ == "__main__":
    text = GUIDE.read_text()
    items = read_items(text)
    for n in sorted({n for _, _, lectures in items for n in lectures}):
        print("synced", sync_lecture(n, items).relative_to(ROOT))
    GUIDE.write_text(sync_index(text, items))
    print(f"{len(items)} items; index written to {GUIDE.relative_to(ROOT)}")
